---
- name: Provision a {{ application_name }} server
  hosts: staging
  sudo: yes
  sudo_user: root
  remote_user: andermic
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/staging.yml
  roles:
    - base
    - db
    - web
