---
- name: Create Sensu vhost in RabbitMQ
  rabbitmq_vhost:
    name: /sensu
    state: present
  when: sensu_server == 'true'

- name: Create Sensu user in RabbitMQ
  rabbitmq_user:
    user: "{{ sensu_user }}"
    password: "{{ sensu_password }}"
    vhost: /sensu
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  when: sensu_server == 'true'

- name: Copy Sensu repo template
  template:
    src: sensu.repo.j2
    dest: /etc/yum.repos.d/sensu.repo
    owner: root
    group: root
    mode: 0644

- name: Install Sensu
  yum:
    name: sensu
    state: present

- name: Copy Sensu server config template
  template:
    src: server_config.json.j2
    dest: /etc/sensu/config.json
    owner: sensu
    group: sensu
    mode: 0644
  when: sensu_server == 'true'

- name: Copy Sensu client config template
  template:
    src: client.json.j2
    dest: /etc/sensu/conf.d/client.json
    owner: sensu
    group: sensu
    mode: 0644
  when: sensu_client == 'true'

- name: Copy Sensu client rabbit config template
  template:
    src: client_rabbit.json.j2
    dest: /etc/sensu/conf.d/rabbit.json
    owner: sensu
    group: sensu
    mode: 0644
  when: sensu_client == 'true'

- name: Install plugin
  get_url:
    url: http://sensuapp.org/docs/0.17/files/check-mem.sh
    dest: /etc/sensu/plugins/check-mem.sh
    owner: sensu
    group: sensu
    mode: 0700

- name: Copy check memory configuration
  template:
    src: check_memory.json.j2
    dest: /etc/sensu/conf.d/check_memory.json
    owner: sensu
    group: sensu
    mode: 0644

- name: Copy default handler
  template:
    src: default_handler.json.j2
    dest: /etc/sensu/conf.d/default_handler.json
    owner: sensu
    group: sensu
    mode: 0644

- name: Ensure permissions on configuration
  file:
    path: /etc/sensu
    recurse: yes
    owner: sensu
    group: sensu
    state: directory

- name: Start Sensu server
  service:
    name: sensu-server
    state: started
    enabled: yes
  when: sensu_server == 'true'

- name: Start Sensu api
  service:
    name: sensu-api
    state: started
    enabled: yes
  when: sensu_server == 'true'

- name: Start Sensu client
  service:
    name: sensu-client
    state: started
    enabled: yes
  when: sensu_client == 'true'


