---
- name: Copy all checks files to client
  copy:
    src: "sensu/plugins/"
    dest: "/etc/sensu/plugins/"
    owner: "{{ sensu_user }}"
    group: "{{ sensu_group }}"
    mode: 0750

- name: Generate client config files
  template:
    src: "client.json.j2"
    dest: "/etc/sensu/conf.d/client.json"
    owner: "{{ sensu_user }}"
    group: "{{ sensu_group }}"
    mode: 0640
    backup: yes
  notify:
    - restart sensu client

- name: Enable sensu-client to survive reboot
  service:
    name: sensu-client
    enabled: yes
    state: started