---
- name: Ensure newrelic directory exists
  apt:
    name: "{{ item }}"
    update_cache: "{{ update_apt_cache }}"
    state: latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Copy newrelic template
  template:
    src: newrelic.ini.j2
    dest: "{{ newrelic_dir }}/{{ application_name }}.newrelic.ini"
    backup: yes
