---

- name: Create the virtualenv
  command: virtualenv {{ virtualenv_path }} --no-site-packages
    creates={{ virtualenv_path }}/bin/activate

- name: Create the application log folder
  file: path={{ application_log_dir }}
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0774
        state=directory

- name: Create the application log file
  command: touch {{ application_log_file }}
    creates={{ application_log_file }}

- name: Create virtualenv postactivate script for env variables
  template: src=virtualenv_postactivate.j2
            dest={{ virtualenv_path }}/bin/postactivate
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0640
            backup=yes

- name: Set permissions on application log file
  file: path={{ application_log_file }}
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        mode=0664
        state=file