---
- name: Create the init script
  template:
    src: gunicorn_init.j2
    dest: "/etc/init/gunicorn-{{ application_name }}.conf"
    backup: yes

- name: Restart Service
  service:
    name: "gunicorn-{{ application_name }}"
    state: started
    enabled: yes
