---
# Application Settings
project_path: "/srv/www/{{ project_name }}"
application_path: "{{ project_path }}/{{ application_name }}"
virtualenv_path: "{{ project_path }}/venv"
application_log_dir: "{{ project_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn.log"
requirements_file: "{{ project_path }}/requirements.txt"

# Gunicorn Settings
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps

# Nginx Settings
nginx_http_port: 80
nginx_https_port: 443
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ project_path }}/static/"
nginx_media_dir: "{{ project_path }}/media/"

# Django Environment Variables
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  SECRET_KEY: "{{ django_secret_key }}"
  STRIPE_PUBLIC_KEY: "{{ stripe_public_key }}"
  STRIPE_SECRET_KEY: "{{ stripe_secret_key }}"
  EMAIL_HOST_PASSWORD: "{{ email_password }}"
  DATABASE_PASSWORD: "{{ db_password }}"
